In [2]:
# PRUEBA GDELTDOC, EJEMPLO de uno de los topics
!pip install gdeltdoc

Requirement already satisfied: gdeltdoc in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (1.5.0)
Requirement already satisfied: pandas>=1.1.4 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from gdeltdoc) (1.5.1)
Requirement already satisfied: requests>=2.25.1 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from gdeltdoc) (2.31.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\picar\appdata\roaming\python\python39\site-packages (from pandas>=1.1.4->gdeltdoc) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.1.4->gdeltdoc) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.1.4->gdeltdoc) (1.26.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.25.1->gdeltdoc) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.25.1->gdeltdoc) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.25.1->gdeltdoc) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\picar\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.25.1->gdeltdoc) (2023.11.17)
Requirement already satisfied: six>=1.5 in c:\users\picar\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas>=1.1.4->gdeltdoc) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
from gdeltdoc import GdeltDoc, Filters
import pandas as pd
f = Filters(
    keyword="Inclusive growth",
    start_date="2018-05-10", # primero he puesto 2014, PERO ME DABA ERROR COMO SI DE ESTE TOPIC NO HUBIESE TODOS LOS AÑOS!!!  REVISAR ESTO!
    end_date="2023-05-11")

# Para meter filtro PAISES, parametro country, en esta pagina salen todos los parametros https://pypi.org/project/gdeltdoc/
# NO HE VISTO NINGUN PARAMETRO PARA EL NUMERO DE PALABRAS (hemos probado min_words, pero no funciona)
# Podemos filtrar una vez encontrados, encontramos una forma:

# Realizar la consulta
documents = GdeltDoc().documents(f)

# Filtrar los documentos por longitud de palabras
filtered_documents = [doc for doc in documents if len(doc['content'].split()) > 500]
df = pd.DataFrame(filtered_documents) # pasando a dataframe solo los filtrados

In [6]:
gd = GdeltDoc()
articles = gd.article_search(f)
df = pd.DataFrame(articles)

In [7]:
# Vamos a visualizar este ejemplo y que tipo de dataframe nos da
df

,url,url_mobile,title,seendate,socialimage,domain,language,sourcecountry
0,https://www.finanznachrichten.de/nachrichten-2...,,The Mastercard Center for Inclusive Growth : H...,20230331T230000Z,https://www.finanznachrichten.de/chart-masterc...,finanznachrichten.de,English,Germany
1,https://www.streetinsider.com/Accesswire/Trevo...,,"Trevor Noah , Melinda French Gates , Samantha ...",20230403T230000Z,,streetinsider.com,English,United States
2,https://www.streetinsider.com/Accesswire/How+M...,,How Mastercard Is Advancing Inclusive Growth,20230331T230000Z,,streetinsider.com,English,United States
3,https://www.wallstreet-online.de/nachricht/167...,https://www.wallstreet-online.de/_amp/nachrich...,How Mastercard Is Advancing Inclusive Growth,20230331T230000Z,https://assets.wallstreet-online.de/_media/126...,wallstreet-online.de,English,Germany
4,https://www.finanznachrichten.de/nachrichten-2...,,The Mastercard Center for Inclusive Growth : H...,20230417T191500Z,https://www.accesswire.com/users/newswire/imag...,finanznachrichten.de,English,Germany
...,...,...,...,...,...,...,...,...
245,https://www.jamaicaobserver.com/latest-news/nh...,https://www.jamaicaobserver.com/latest-news/nh...,NHT to introduce new financing model - Jamaica...,20230214T190000Z,https://imengine.public.prod.jam.navigacloud.c...,jamaicaobserver.com,English,Jamaica
246,https://www.jamaicaobserver.com/news/nht-to-in...,https://www.jamaicaobserver.com/news/nht-to-in...,NHT to introduce new financing model - Jamaica...,20230215T060000Z,https://imengine.public.prod.jam.navigacloud.c...,jamaicaobserver.com,English,Jamaica
247,https://www.devdiscourse.com/article/internati...,https://www.devdiscourse.com/article/internati...,Chinese bank to refinance USD 500 million loan...,20230316T184500Z,https://www.devdiscourse.com/remote.axd?https:...,devdiscourse.com,English,China
248,http://french.china.org.cn/foreign/txt/2023-02...,,La FAO promet de renforcer son partenariat ave...,20230217T221500Z,,french.china.org.cn,French,China
249,https://www.newstimes.com/news/article/new-hav...,,New Haven State House music venue to close its...,20230324T191500Z,https://s.hdnux.com/photos/01/21/03/00/2124596...,newstimes.com,English,United States

In [8]:
# para analizar el tono
tone_results = gd.timeline_search("timelinetone", f)
tone_results
# significado, LOS NEGATIVOS TIENEN TONOS NEGATIVOS, LOS POSITIVOS POSITIVOS Y LOS CERCANOS A CERO NEUTROS

                      datetime  Average Tone
0    2018-05-10 00:00:00+00:00        1.9743
1    2018-05-11 00:00:00+00:00        2.0551
2    2018-05-12 00:00:00+00:00        1.6104
3    2018-05-13 00:00:00+00:00        1.0008
4    2018-05-14 00:00:00+00:00        1.3417
...                        ...           ...
1821 2023-05-07 00:00:00+00:00        1.7944
1822 2023-05-08 00:00:00+00:00        2.1669
1823 2023-05-09 00:00:00+00:00        1.2283
1824 2023-05-10 00:00:00+00:00        1.7306
1825 2023-05-11 00:00:00+00:00        3.0733

[1826 rows x 2 columns]

In [9]:
# Recordemos que los datos son POR DIAS, habria que agrupar por semana y por trimestre!! (lo solicitado por randbee)
# MUY IMPORTANTE QUE REGULARICEMOS BIEN, QUE NORMALICEMOS CORRECTAMENTE!! (con criterio igual que google trends y variable respuesta)

In [10]:
# y para la popularidad
popularity_results = gd.timeline_search("timelinevol", f)
popularity_results

                      datetime  Volume Intensity
0    2018-05-10 00:00:00+00:00            0.0172
1    2018-05-11 00:00:00+00:00            0.0138
2    2018-05-12 00:00:00+00:00            0.0081
3    2018-05-13 00:00:00+00:00            0.0077
4    2018-05-14 00:00:00+00:00            0.0193
...                        ...               ...
1821 2023-05-07 00:00:00+00:00            0.0086
1822 2023-05-08 00:00:00+00:00            0.0113
1823 2023-05-09 00:00:00+00:00            0.0223
1824 2023-05-10 00:00:00+00:00            0.0240
1825 2023-05-11 00:00:00+00:00            0.0165

[1826 rows x 2 columns]

Popularidad:
La popularidad mide la cantidad de menciones o cobertura de un tema en los artículos.
En nuestra tabla, los valores en la columna “Volume Intensity” representan la popularidad relativa de los artículos en un intervalo de tiempo específico.
Estos valores son proporcionales dentro del conjunto de artículos monitoreados por GDELT.
Rango de Popularidad:
Los valores en la columna “Volume Intensity” pueden variar entre 0 y 1.
Un valor de 0.1839 significa que, en ese intervalo de tiempo, los artículos relacionados con el tema tenían una popularidad relativa del 18.39% en comparación con el total de artículos monitoreados.

In [11]:
# OJO, TENEMOS QUE REVISAR LOS FILTROS QUE SE NOS PIDIO, QUE TENGA MAS DE 500 PALABRAS, 
# tambien surgen dudas de lo de normalizarlos luego (¿¿solo entre los articulos seleccionados??)

INFORMACION RANDBEE NUEVO CAMBIO
Los datos de Google Trends se debería descargar para el periodo "weekly", y que los datos diarios de GDELT se deberían agrupar mediante promediado a datos semanales. El modelo se construiría entonces con datos para los cuartos de año, generados a partir de los datos semanales de Google Trends y GDELT como promedios, y con los datos por cuarto de año de la variable respuesta. Posteriormente, una vez calibrado el modelo, se harían predicciones con el mismo sobre los datos semanales de Google Trends y de GDELT.